# Javascript Node CircleCI 2.0 configuration file
version: 2

default: &default
  working_directory: ~/aida
  docker:
    - image: circleci/node:8.12

aliases:
  - &restore-cache
    keys:
      - v2-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
      # Fallback in case checksum fails
      - v2-dependencies-{{ .Branch }}-

  - &save-cache
    paths:
      - node_modules
    key: v2-dependencies-{{ .Branch }}-{{ checksum "package.json" }}


  - &filter-only-master
      branches:
        only:
          - master

  - &filter-ignore-gh-pages
      branches:
        ignore: 
          - gh-pages

jobs:
  test-all:
    <<: *default
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: npm install
      - run: npm run bootstrap
      - save_cache: *save-cache
      - run: npm run build
      - run: npm run test

  deploy-website:
    <<: *default
    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "sradevski@live.com"
            git config --global user.name "Stevche Radevski"
            echo "machine github.com login sradevski password $GITHUB_TOKEN" > ~/.netrc
            cd website && npm install && GIT_USER=sradevski npm run publish-gh-pages

workflows:
  version: 2
  test:
    jobs:
      - test-all:
          filters: *filter-ignore-gh-pages

  website_deploy:
    jobs:
      - deploy-website:
          type: approval
          filters: *filter-only-master
