const rootProperties = {
  openapi: '3',
  info: 'API generated by validstack',
};

export default function swagger(definitions) {
  const swaggerDocs = {};
  return { ...definitions, swaggerDocs: swaggerDocs };
}
