import mockHttp from '@aida/consumer-faked-http';
//Endpoints json generated by @aida/injector-faked-routes
import fakedEndpoints from './endpoints.json';
import { setBaseRoute } from './routesMapper';

export default function configureApp(env) {
  envSetup[env]();
}

const envSetup = {
  development: () => {
    //Setup aida to intercept and mock all defined requests, specifying the root dev url to which you will do your requests. We also pass some options, in this case a fixed ms delay of the responses
    const baseRoute = 'http://localhost:4000';
    setBaseRoute(baseRoute);
    mockHttp(fakedEndpoints, baseRoute, { timing: 1500 });
  },
  production: () => {},
};
