import mockHttp from '@aida/consumer-faked-http';
//Endpoints json generated by @aida/injector-faked-data-routes
import fakedEndpoints from './endpoints.json';

export default function configureApp(env) {
  envSetup[env]();
}

const envSetup = {
  development: () => {
    //Setup aida to intercept and mock all defined requests, specifying the root dev url to which you will do your requests.
    mockHttp(fakedEndpoints, 'http://localhost:4000/');
  },
  production: () => {},
};
